sjsonnet.Error: Internal Error
    at [std.parseJson].(sjsonnet/test/resources/test_suite/error.parse_json.jsonnet:1:14)
Caused by: ujson.ParseException: expected json value got "b" at index 0
    at ujson.ParseException$.apply(Exceptions.scala:6)
    at ujson.CharParser.die(CharParser.scala:98)
    at ujson.CharParser.parseTopLevel0(CharParser.scala:353)
    at ujson.CharParser.parseTopLevel(CharParser.scala:323)
    at ujson.CharParser.parse(CharParser.scala:72)
    at ujson.StringParser$.transform(StringParser.scala:28)
    at sjsonnet.Std$ParseJson$.evalRhs(Std.scala:989)
    at sjsonnet.Evaluator.visitApplyBuiltin1(Evaluator.scala:270)
    at sjsonnet.Evaluator.visitExpr(Evaluator.scala:40)
    at sjsonnet.Interpreter.evaluate$$anonfun$2$$anonfun$1(Interpreter.scala:177)
    at sjsonnet.Interpreter.sjsonnet$Interpreter$$handleException(Interpreter.scala:163)
    at sjsonnet.Interpreter.evaluate$$anonfun$2(Interpreter.scala:177)
    at scala.util.Either.flatMap(Either.scala:360)
    at sjsonnet.Interpreter.evaluate(Interpreter.scala:175)
    at sjsonnet.Interpreter.interpret0(Interpreter.scala:158)
    at sjsonnet.SjsonnetMain$.renderNormal$$anonfun$1(SjsonnetMain.scala:157)
    at sjsonnet.SjsonnetMain$.writeToFile(SjsonnetMain.scala:131)
    at sjsonnet.SjsonnetMain$.renderNormal(SjsonnetMain.scala:155)
    at sjsonnet.SjsonnetMain$.mainConfigured(SjsonnetMain.scala:332)
    at sjsonnet.SjsonnetMain$.$anonfun$30$$anonfun$1(SjsonnetMain.scala:85)
    at scala.util.Either.flatMap(Either.scala:360)
    at sjsonnet.SjsonnetMain$.$anonfun$30(SjsonnetMain.scala:84)
    at scala.util.Either.flatMap(Either.scala:360)
    at sjsonnet.SjsonnetMain$.main0(SjsonnetMain.scala:77)
    at sjsonnet.SjsonnetMain$.main(SjsonnetMain.scala:44)
    at sjsonnet.SjsonnetMain.main(SjsonnetMain.scala)

